# Generated by Django 6.0 on 2025-12-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=6)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=72)),
                ('job', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Agent', 'Agent'), ('Customer', 'Customer')], default='Customer')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.appuser')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketpriority')),
                ('status', models.ForeignKey(default='TODO', on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_description', models.TextField()),
                ('current_description', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.appuser')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status', to='ticketing.ticketstatus')),
                ('previous_state', models.ForeignKey(default='TODO', on_delete=django.db.models.deletion.CASCADE, related_name='old_status', to='ticketing.ticketstatus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(fields=('account_id', 'email'), name='unique_agent'),
        ),
    ]
