# Generated by Django 6.0 on 2025-12-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=6)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=72)),
                ('job_title', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Agent', 'Agent'), ('Customer', 'Customer')], default='Customer')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('ticket_category', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('assignee_id', models.ForeignKey(blank=True, limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='ticketing.appuser')),
                ('creator_id', models.ForeignKey(limit_choices_to={'role': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='ticketing.appuser')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketpriority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ticketing.ticket')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.appuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(fields=('account_id', 'email'), name='unique_agent'),
        ),
    ]
