# Generated by Django 6.0 on 2025-12-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='changed_at',
        ),
    ]
