# Generated by Django 6.0 on 2025-12-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_ticket_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
