# Generated by Django 5.2.9 on 2025-12-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_alter_account_id_alter_appuser_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
