# Generated by Django 5.2.9 on 2025-12-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_appuser_deleted_at_appuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Customer', 'Customer'), ('System', 'System')], default='Customer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='purpose',
            field=models.CharField(choices=[('Ticket Created', 'Ticket Created'), ('Ticket Assigned', 'Ticket Assigned'), ('Comment', 'Comment')], max_length=30),
        ),
    ]
